### ISSUE TITLE
integrity failure

### ISSUE THREAD

**Issue by Instantnoodles-madman** [prasunroy/stefann#10]
When I run the code, it is reporting the error `integrity failure`.

**Comment by dietercastel** [comment]
I had the same but @prasunroy found a fix described in this [closed] thread. https://github.com/prasunroy/stefann/issues/8

**Comment by dietercastel** [comment]
I reopened said issue so it's not hidden by default.

**Comment by prasunroy** [comment]
This error specifically occurs when models and checkpoints are not found by STEFANN. Follow [Step 1](https://github.com/prasunroy/stefann#step-1-download-models-and-pretrained-checkpoints-into-releasemodels-directory) of [Quick test](https://github.com/prasunroy/stefann#boom-quick-test). You need to put the models and checkpoints (4 files) into `release/models` directory.

**Comment by Instantnoodles-madman** [comment]
Thanks for your reply.
I relsoved the problem. The path to the downloaded files was wrong.
