### ISSUE TITLE
How to use the tool

### ISSUE THREAD

**Issue by Instantnoodles-madman** [prasunroy/stefann#11]
After I run the command `python stefann.py` and open an image, what are the steps to replace the characters in that image?

**Comment by dietercastel** [comment]
[This readme will help](https://github.com/prasunroy/stefann/blob/master/release/readme.html).

It might be handy to have it mentioned in the main repository readme for ease of access.

**Comment by Instantnoodles-madman** [comment]
OK. Thank you. I will read the readme in detail.
