### ISSUE TITLE
Is it processing only one image at a time?

### ISSUE THREAD

**Issue by Instantnoodles-madman** [prasunroy/stefann#12]
Is it necessary to restart the program after processing one image?
How to run it continuously?

**Comment by prasunroy** [comment]
No, you don't have to restart the program after processing one image. After editing is finished or cancelled the main GUI will return to image selection window. From there you can open another image as before. For keyboard controls you can check the in-built `README` from the main GUI (opens in a separate browser window).

Watch [this video](https://www.youtube.com/watch?v=HBOt9Hb__AY) for a demo.
>NOTE: To enhance the viewing experience, the required tunings are not shown in the video. Only the final values for these parameters, i.e. `Inverse Binarization`, `Binarization Threshold` and `Minimum Allowed Contour Area`, are shown for each image. These values can be easily set using the keyboard controls mentioned in the in-built `README`.

>The `README` can also be found [here](https://github.com/prasunroy/stefann/blob/master/release/readme.html).
