### ISSUE TITLE
How to edit numbers?

### ISSUE THREAD

**Issue by ilovecv** [prasunroy/stefann#13]
Hi,

Thanks for sharing your awesome work! I am wondering if you have a pretrained model to edit numbers? Thanks.

**Comment by prasunroy** [comment]
Hi,

Thanks for your interest in our work. Unfortunately, we do not have a pretrained model for numeric characters to release at this point. Although we trained such models while preparing results for the paper but there were no official decision taken to release them.

However, you should be able to train such a model very easily with the provided code. In `fannet.py` change line `48` and `49` as follows:
```python
SOURCE_CHARS = '0123456789'
TARGET_CHARS = '0123456789'
```
Before training, you should prepare some random test pairs for numerals and replace the default letter pairs in `datasets/fannet/pairs`. You need to follow the filename convention as described in the [README](https://github.com/prasunroy/stefann#pushpin-description-of-datasetsfannet).
