### ISSUE TITLE
About character replacement

### ISSUE THREAD

**Issue by BangdongChen** [prasunroy/stefann#16]
Thank you very much for your contribution in this field.
I still have some questions about the character replacement part. As you said in the paper, when training fannet and colornet, the input character size is 64*64, but when performing character replacement in a real scene, some characters are much larger in size 64*64 (for example, 128*128), how did you solve this situation? Is it to directly resize the generated characters to 128*128 or some other way?

**Comment by prasunroy** [comment]
The character replacement policy involves a few steps. I try to explain with an example.

We assume all characters are in uppercase and well-separated. Let us consider the following image:
![01](https://user-images.githubusercontent.com/38404108/115927674-6c167380-a4a2-11eb-94b8-e64aee6e16f1.png)
Here we want to replace `U` (marked by red border) by `I` i.e. edit `FUND` to `FIND`.

#### 1. Resizing the generated target character
Assume the dimension of the minimum bounding box of source character `U` is `w x h`. This bounding box is padded and resized maintaining its aspect ratio to a dimension of `64 x 64`. The resized source character is sequentially passed through FANnet and Colornet to produce the target character having the same dimension of `64 x 64`. In general, uppercase letters have same height but different widths. For this reason, we resize the target character from `64 x 64` to `h x h`. Assume the dimension of the minimum bounding box of resized target character `I` is `w1 x h`.
![02](https://user-images.githubusercontent.com/38404108/115931364-9cf9a700-a4a8-11eb-979f-2e8a2919e570.png)
> In our case, we resize the target character directly. In most of our application scenarios, this does not create any significant visual distortion. For much larger upscaling, we recommend to use a super resolution generative network such as [ESRGAN](https://openaccess.thecvf.com/content_eccv_2018_workshops/w25/html/Wang_ESRGAN_Enhanced_Super-Resolution_Generative_Adversarial_Networks_ECCVW_2018_paper.html).

#### 2. Replacing the source character
We perform the replacement such that the centres of both the bounding boxes (marked by red dots) are aligned. Consequently, this will create either **blank spaces** (if `w1 < w`) or **overlaps** (if `w1 > w`) between the target character and the neighbouring characters.
![03](https://user-images.githubusercontent.com/38404108/115947381-ce906380-a4e4-11eb-901a-1158aaa24275.png)

#### 3. Adjusting the region around the target character
Estimating the width of the unwanted region is fairly straightforward.
![04](https://user-images.githubusercontent.com/38404108/115947700-03051f00-a4e7-11eb-9ab5-535c4e8b5d61.png)
Width of the unwanted region in each side, `d = |w1 - w| / 2`.
Now, depending on whether there are **blank spaces** or **overlaps**, the neighbouring characters need to be ***pushed towards*** or ***pulled outwards*** the target character.
![05](https://user-images.githubusercontent.com/38404108/115948015-334dbd00-a4e9-11eb-8697-aec2308bfdaf.png)
One way to achieve this is to apply [Seam Carving](https://dl.acm.org/doi/10.1145/1275808.1276390) by either deleting or inserting `d` *seams* on each side of the target character.
> While seam carving can produce visually appealing results, the slow execution speed and an associated patent limit its applicability in real-time scenarios. Thus, we perform this step in an alternative way.

#### 4. An alternative approach to Seam Carving
As we can deterministically estimate `d`, each character can be translated to a new position followed by ***inpainting*** the old position.
![06](https://user-images.githubusercontent.com/38404108/115949179-cf2ef700-a4f0-11eb-9791-71493816f46a.png)
> In most of our examples, `d` is fairly small so we simply use a generic inpainting without any noticeable visual distortion. For significantly larger characters and more complex backgrounds this can be improved by incorporating a neural inpainting technique such as [this](https://openaccess.thecvf.com/content_ECCV_2018/html/Guilin_Liu_Image_Inpainting_for_ECCV_2018_paper.html).

I hope this illustration will clear your doubts about the character replacement policy. Thank you for your interest in our work! :)
