### ISSUE TITLE
How to install Tensorflow 2.1.0 in  Conda Enviroment.

### ISSUE THREAD

**Issue by Vikrant-Deshmukh** [prasunroy/stefann#2]
I can't seem to find a 2.1.0 version of TensorFlow for conda. Can you please provide me the links for the same.

**Comment by prasunroy** [comment]
Have you followed the [installation instructions](https://github.com/prasunroy/stefann#boom-quick-installation)?
In my case it's working without any issue on both Linux and Windows.
:neutral_face:

**Comment by Vikrant-Deshmukh** [comment]
Yes Sorry for the trouble.I was on a Mac.I used Bootcamp to install Windows and now it works. 👍
