### ISSUE TITLE
Colab

### ISSUE THREAD

**Issue by xstrauss2** [prasunroy/stefann#22]
Can anyone make a Colab or easy-to-run version please? 🙏

**Comment by prasunroy** [comment]
While I won't be able to work on a Colab notebook anytime soon, two demo notebooks for FANnet and Colornet are already available at Kaggle. Please check the following links.

* FANnet -- https://www.kaggle.com/code/prasunroy/starter-1-font-generation-stefann-cvpr-2020
* Colornet -- https://www.kaggle.com/code/prasunroy/starter-2-color-transfer-stefann-cvpr-2020

**Comment by xstrauss2** [comment]
So can I change the texts in the images with these links? And how?

**Comment by prasunroy** [comment]
Unfortunately NO. These notebooks demonstrate the training mechanism of FANnet and Colornet. The fully integrated pipeline is interactive and requires user specified adjustments at runtime. So, it is difficult to implement all such functionalities into a notebook. To use it as an application, please follow the [instructions](https://github.com/prasunroy/stefann#boom-quick-test) in the README.
