### ISSUE TITLE
Process stuck after conda env create -f release/env_cpu.yml

### ISSUE THREAD

**Issue by Vikrant-Deshmukh** [prasunroy/stefann#3]
It shows:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: /
```
It's not progressing forward for a long time. How long does it take to run this process? Or is there any other solution?

**Comment by prasunroy** [comment]
This depends on your network connection and the geographical location of the mirror site. There is no clear answer to this. I personally experienced total installation time to be anywhere between 2-10 minutes on different occassions.

>If you like to run natively on OSX, you may check [this](https://github.com/prasunroy/stefann/pull/1) pull request. It's not merged to `master` yet but it might be useful.
